import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Star, Camera, X, Send, Edit, Eye, RefreshCw, User, FileText, Image, CheckCircle, AlertCircle } from 'lucide-react';
import { format } from 'date-fns';
import { zhCN } from 'date-fns/locale';
import { useAuthStore, useOrderStore } from '@/store';
import StarRating from '@/components/ui/StarRating';
import { mockOrders, getFeederById, getServiceName, getStatusText, getStatusColor } from '@/data/mockData';
import type { Review, Order, AfterSalesStatus } from '@/data/types';

const refundReasons = ['服务未按时完成', '服务质量不满意', '宠物出现异常', '其他原因'];
const ratingLabels = ['总体评分', '服务态度', '专业程度', '准时程度'];
const ratingKeys = ['overallRating', 'attitudeRating', 'professionalRating', 'punctualityRating'] as const;
const afterSalesStatusMap: Record<AfterSalesStatus, { label: string; color: string }> = { none: { label: '无售后', color: 'bg-warm-100 text-warm-600' }, pending: { label: '待处理', color: 'bg-amber-100 text-amber-600' }, processing: { label: '处理中', color: 'bg-primary-100 text-primary-600' }, resolved: { label: '已解决', color: 'bg-green-100 text-green-600' }, rejected: { label: '已拒绝', color: 'bg-red-100 text-red-600' } };
const tabs = [{ id: 'review', label: '发表评价', icon: Star }, { id: 'aftersales', label: '售后管理', icon: RefreshCw }, { id: 'myreviews', label: '我的评价', icon: FileText }] as const;

type TabId = typeof tabs[number]['id'];
type FormData = { overallRating: number; attitudeRating: number; professionalRating: number; punctualityRating: number; content: string; photos: string[]; isAnonymous: boolean };
const initForm: FormData = { overallRating: 5, attitudeRating: 5, professionalRating: 5, punctualityRating: 5, content: '', photos: [], isAnonymous: false };

export default function ReviewAftersalesPage() {
  const { currentUser } = useAuthStore();
  const { reviews, addReview } = useOrderStore();
  const [activeTab, setActiveTab] = useState<TabId>('review');
  const [showRefund, setShowRefund] = useState(false);
  const [selectedOrder, setSelectedOrder] = useState<Order | null>(null);
  const [editingReview, setEditingReview] = useState<Review | null>(null);
  const [viewingReview, setViewingReview] = useState<Review | null>(null);
  const [formData, setFormData] = useState<FormData>(initForm);
  const [refundForm, setRefundForm] = useState({ reason: '', amount: '', description: '' });
  const userOrders = currentUser ? mockOrders.filter(o => o.userId === currentUser.id && o.status === 'completed') : [];
  const afterSalesOrders = currentUser ? mockOrders.filter(o => o.userId === currentUser.id && o.status !== 'cancelled') : [];
  const myReviews = currentUser ? reviews.filter(r => r.userId === currentUser.id) : [];
  const fmt = (d: string, p: string) => format(new Date(d), p, { locale: zhCN });
  const resetForm = () => { setFormData(initForm); setSelectedOrder(null); setEditingReview(null); };

  const handleSubmitReview = () => { if (!selectedOrder || !currentUser) return; addReview({ orderId: selectedOrder.id, ...formData, afterSalesStatus: 'none' }); resetForm(); };
  const handleEditReview = (review: Review) => { setEditingReview(review); setFormData({ overallRating: review.overallRating, attitudeRating: review.attitudeRating, professionalRating: review.professionalRating, punctualityRating: review.punctualityRating, content: review.content, photos: review.photos, isAnonymous: review.isAnonymous }); const order = mockOrders.find(o => o.id === review.orderId); if (order) setSelectedOrder(order); setActiveTab('review'); };

  const renderStarRatings = () => (<div className="space-y-5">{ratingLabels.map((label, idx) => (<div key={label} className={`flex items-center justify-between ${idx === 0 ? 'py-3 border-b border-warm-100' : ''}`}><span className="text-warm-600">{label}</span><StarRating rating={formData[ratingKeys[idx]]} onRatingChange={(r) => setFormData({ ...formData, [ratingKeys[idx]]: r })} size={idx ? 'md' : 'lg'} /></div>))}</div>);

  const renderReviewForm = () => (<div className="card"><div className="flex items-center justify-between mb-6"><div><h3 className="font-medium text-warm-800">评价 {selectedOrder && getFeederById(selectedOrder.feederId)?.name}</h3><p className="text-sm text-warm-500 mt-1">{selectedOrder && `${getServiceName(selectedOrder.serviceType)} · ${fmt(selectedOrder.scheduledDate, 'yyyy年MM月dd日')}`}</p></div><button onClick={resetForm} className="text-warm-400 hover:text-warm-600"><X className="w-5 h-5" /></button></div>{renderStarRatings()}<div className="space-y-5 mt-5"><textarea value={formData.content} onChange={(e) => setFormData({ ...formData, content: e.target.value })} placeholder="分享您的服务体验..." className="input-field min-h-24 resize-none" /><button className="flex items-center gap-2 px-4 py-2 border-2 border-dashed border-warm-200 rounded-xl text-warm-500 hover:border-primary-400 hover:text-primary-500 transition-colors"><Camera className="w-5 h-5" /><span className="text-sm">上传照片</span></button><label className="flex items-center gap-3 cursor-pointer"><input type="checkbox" checked={formData.isAnonymous} onChange={(e) => setFormData({ ...formData, isAnonymous: e.target.checked })} className="w-5 h-5 rounded border-warm-300 text-primary-500 focus:ring-primary-500" /><span className="text-warm-600 flex items-center gap-2"><User className="w-4 h-4" />匿名评价</span></label><button onClick={handleSubmitReview} disabled={!formData.content.trim()} className="btn-primary w-full flex items-center justify-center gap-2 disabled:opacity-50"><Send className="w-5 h-5" />{editingReview ? '保存修改' : '提交评价'}</button></div></div>);

  const renderReviewTab = () => (<div className="space-y-6">{!selectedOrder ? (<div className="space-y-3"><h3 className="font-medium text-warm-700">选择待评价订单</h3>{userOrders.length === 0 ? (<div className="card text-center py-12"><CheckCircle className="w-12 h-12 text-warm-300 mx-auto mb-3" /><p className="text-warm-500">暂无待评价订单</p></div>) : (userOrders.map((order) => (<motion.div key={order.id} whileTap={{ scale: 0.98 }} onClick={() => setSelectedOrder(order)} className="card cursor-pointer card-hover"><div className="flex items-center justify-between"><div><p className="font-medium text-warm-800">{getServiceName(order.serviceType)}</p><p className="text-sm text-warm-500 mt-1">{getFeederById(order.feederId)?.name} · {fmt(order.scheduledDate, 'MM-dd')}</p></div><span className="text-primary-500 text-sm">去评价 →</span></div></motion.div>)))}</div>) : (renderReviewForm())}</div>);

  const renderAftersalesTab = () => (<div className="space-y-4">{afterSalesOrders.length === 0 ? (<div className="card text-center py-16"><AlertCircle className="w-16 h-16 text-warm-300 mx-auto mb-4" /><p className="text-warm-500">暂无订单</p></div>) : (afterSalesOrders.map((order) => { const review = reviews.find(r => r.orderId === order.id); const statusInfo = afterSalesStatusMap[review?.afterSalesStatus || 'none']; return (<motion.div key={order.id} initial={{ opacity: 0, x: -20 }} animate={{ opacity: 1, x: 0 }} className="card"><div className="flex items-start justify-between mb-4"><div><div className="flex items-center gap-2"><h4 className="font-medium text-warm-800">{getServiceName(order.serviceType)}</h4><span className={`badge ${statusInfo.color}`}>{statusInfo.label}</span></div><p className="text-sm text-warm-500 mt-1">{getFeederById(order.feederId)?.name} · {fmt(order.scheduledDate, 'yyyy-MM-dd HH:mm')}</p><p className="text-sm text-warm-400 mt-1">订单号：{order.id}</p></div><span className={`badge badge-${getStatusColor(order.status)}`}>{getStatusText(order.status)}</span></div><div className="flex items-center justify-between pt-4 border-t border-warm-100"><span className="text-lg font-medium text-primary-600">¥{order.totalPrice}</span><button onClick={() => { setSelectedOrder(order); setShowRefund(true); }} className="btn-outline text-sm px-4 py-2">申请退款</button></div></motion.div>); }))}</div>);

  const renderMyReviewsTab = () => (<div className="space-y-4">{myReviews.length === 0 ? (<div className="card text-center py-16"><FileText className="w-16 h-16 text-warm-300 mx-auto mb-4" /><p className="text-warm-500">暂无评价记录</p></div>) : (myReviews.map((review) => { const order = mockOrders.find(o => o.id === review.orderId); return (<motion.div key={review.id} initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="card"><div className="flex items-start justify-between mb-3"><div className="flex items-center gap-3">{review.isAnonymous ? (<div className="w-10 h-10 rounded-full bg-warm-200 flex items-center justify-center"><User className="w-5 h-5 text-warm-500" /></div>) : (<img src={currentUser?.avatar} alt="avatar" className="w-10 h-10 rounded-full object-cover" />)}<div><p className="font-medium text-warm-800">{review.isAnonymous ? '匿名用户' : currentUser?.name}</p><p className="text-xs text-warm-400">{fmt(review.createdAt, 'yyyy-MM-dd HH:mm')}</p></div></div><div className="flex gap-2"><button onClick={() => setViewingReview(review)} className="p-2 text-warm-400 hover:text-secondary-500 transition-colors"><Eye className="w-4 h-4" /></button><button onClick={() => handleEditReview(review)} className="p-2 text-warm-400 hover:text-primary-500 transition-colors"><Edit className="w-4 h-4" /></button></div></div><div className="flex items-center gap-2 mb-3"><StarRating rating={review.overallRating} readonly size="sm" /><span className="text-sm text-warm-500">{order && getServiceName(order.serviceType)}</span></div><p className="text-warm-600 text-sm line-clamp-3">{review.content}</p>{review.photos.length > 0 && (<div className="flex gap-2 mt-3">{review.photos.map((photo, idx) => (<img key={idx} src={photo} alt="review" className="w-16 h-16 rounded-lg object-cover" />))}</div>)}</motion.div>); }))}</div>);

  const renderRefundModal = () => (<AnimatePresence>{showRefund && (<motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4" onClick={() => setShowRefund(false)}><motion.div initial={{ scale: 0.9, opacity: 0 }} animate={{ scale: 1, opacity: 1 }} exit={{ scale: 0.9, opacity: 0 }} onClick={(e) => e.stopPropagation()} className="bg-white rounded-2xl p-6 w-full max-w-md max-h-[90vh] overflow-y-auto"><div className="flex items-center justify-between mb-6"><h3 className="text-xl font-display text-warm-800">申请退款</h3><button onClick={() => setShowRefund(false)} className="text-warm-400 hover:text-warm-600"><X className="w-6 h-6" /></button></div><div className="space-y-5"><div><label className="block text-sm font-medium text-warm-700 mb-2">退款原因</label><div className="space-y-2">{refundReasons.map((reason) => (<button key={reason} onClick={() => setRefundForm({ ...refundForm, reason })} className={`w-full text-left px-4 py-3 rounded-xl border-2 transition-all ${refundForm.reason === reason ? 'border-primary-500 bg-primary-50 text-primary-700' : 'border-warm-200 hover:border-primary-300'}`}>{reason}</button>))}</div></div><input type="number" value={refundForm.amount} onChange={(e) => setRefundForm({ ...refundForm, amount: e.target.value })} placeholder={`退款金额（最多¥${selectedOrder?.totalPrice || 0}）`} className="input-field" /><textarea value={refundForm.description} onChange={(e) => setRefundForm({ ...refundForm, description: e.target.value })} placeholder="请详细描述您遇到的问题..." className="input-field min-h-20 resize-none" /><button className="flex items-center gap-2 px-4 py-2 border-2 border-dashed border-warm-200 rounded-xl text-warm-500 hover:border-primary-400 hover:text-primary-500 transition-colors"><Image className="w-5 h-5" /><span className="text-sm">上传凭证</span></button><button onClick={() => { setShowRefund(false); setRefundForm({ reason: '', amount: '', description: '' }); }} disabled={!refundForm.reason || !refundForm.amount} className="btn-primary w-full disabled:opacity-50">提交申请</button></div></motion.div></motion.div>)}</AnimatePresence>);

  const renderViewModal = () => (<AnimatePresence>{viewingReview && (<motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4" onClick={() => setViewingReview(null)}><motion.div initial={{ scale: 0.9, opacity: 0 }} animate={{ scale: 1, opacity: 1 }} exit={{ scale: 0.9, opacity: 0 }} onClick={(e) => e.stopPropagation()} className="bg-white rounded-2xl p-6 w-full max-w-md max-h-[90vh] overflow-y-auto"><div className="flex items-center justify-between mb-6"><h3 className="text-xl font-display text-warm-800">评价详情</h3><button onClick={() => setViewingReview(null)} className="text-warm-400 hover:text-warm-600"><X className="w-6 h-6" /></button></div><div className="space-y-4">{ratingLabels.map((label, idx) => (<div key={label} className="flex items-center gap-2"><span className="text-warm-600">{label}</span><StarRating rating={viewingReview[ratingKeys[idx]]} readonly /></div>))}<div className="pt-4 border-t border-warm-100"><p className="text-warm-600">{viewingReview.content}</p></div>{viewingReview.photos.length > 0 && (<div className="grid grid-cols-3 gap-2">{viewingReview.photos.map((photo, idx) => (<img key={idx} src={photo} alt="review" className="w-full aspect-square rounded-lg object-cover" />))}</div>)}<p className="text-sm text-warm-400">评价时间：{fmt(viewingReview.createdAt, 'yyyy年MM月dd日 HH:mm')}</p></div></motion.div></motion.div>)}</AnimatePresence>);

  return (<div className="min-h-screen bg-warm-50 pb-8"><div className="gradient-bg pt-8 pb-6 px-4"><div className="container mx-auto"><h1 className="text-3xl font-display text-warm-800 mb-2">评价售后</h1><p className="text-warm-500">评价服务质量，管理售后需求</p></div></div><div className="container mx-auto px-4"><div className="flex gap-2 mb-6 overflow-x-auto scrollbar-hide py-2">{tabs.map((tab) => { const Icon = tab.icon; const isActive = activeTab === tab.id; return (<motion.button key={tab.id} onClick={() => setActiveTab(tab.id)} className={`flex items-center gap-2 px-5 py-2.5 rounded-xl whitespace-nowrap transition-all ${isActive ? 'bg-gradient-to-r from-secondary-400 to-secondary-500 text-white shadow-soft' : 'bg-white text-warm-600 hover:bg-warm-100'}`} whileTap={{ scale: 0.95 }}><Icon className="w-4 h-4" /><span className="font-medium">{tab.label}</span></motion.button>); })}</div><AnimatePresence mode="wait"><motion.div key={activeTab} initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -20 }} transition={{ duration: 0.3 }}>{activeTab === 'review' && renderReviewTab()}{activeTab === 'aftersales' && renderAftersalesTab()}{activeTab === 'myreviews' && renderMyReviewsTab()}</motion.div></AnimatePresence></div>{renderRefundModal()}{renderViewModal()}</div>);
}
